#"I pledge my honor that I have abided by the Stevens honor system" - igomez1 Ian Gomez
cs392_thread : cs392_thread.o 
	gcc -pthread -o cs392_thread cs392_thread.o
cs392_thread.o: cs392_thread.c
	gcc -c cs392_thread.c
clean:
	rm *.o cs392_thread
